{
  "hash": "23ecaa8ced257364e206f8c0ec7989d1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Chapter 3: Econometric Modelling\"\n---\n\n\n\n\n\n# Introduction\n\n## Definition and Concepts\n\n**Econometric modelling** is a branch of economics that employs statistical methods to analyse economic phenomena, forecast future trends, and evaluate economic policies. It combines **economic theory**, **mathematics**, and **statistical techniques** to quantify and understand the relationships between economic variables.\n\n::: {.callout-note}\nEconometric models go beyond univariate time series methods — they explain *why* a variable behaves as it does by relating it to other economic variables (its *determinants*). This gives forecasts a causal interpretation, which is valuable for policy analysis.\n:::\n\n## Purpose\n\nEconometric models are used to:\n\n- Test economic theories and hypotheses.\n- Predict future economic variables and trends.\n- Assess the impact of policy changes or external shocks on the economy.\n- Make informed decisions in business, finance, and public policy.\n\n## Applications of Econometric Modelling\n\n| Application Area | Example |\n|---|---|\n| **Macroeconomic Forecasting** | Central banks forecast GDP growth, inflation, unemployment rates, and interest rates using large structural models. |\n| **Financial Markets** | The Capital Asset Pricing Model (CAPM) and Arbitrage Pricing Theory (APT) estimate expected asset returns based on risk. |\n| **Labour Economics** | Researchers use difference-in-differences and regression discontinuity designs to evaluate minimum wage laws. |\n| **Health Economics** | Instrumental variables and propensity score matching address endogeneity in evaluating healthcare interventions. |\n| **Environmental Economics** | Panel data and spatial econometrics assess the effectiveness of environmental regulations on economic growth. |\n| **Marketing & Consumer Behaviour** | Discrete choice models and time series analysis forecast consumer demand and advertising effectiveness. |\n\n---\n\n# Basic Structure of Econometric Model\n\n## General Form\n\nThe variables used in econometric models are:\n\n- **Dependent variable** ($y_t$): the variable we want to explain or forecast.\n- **Independent (explanatory) variables** ($x_{1t}, x_{2t}, \\ldots, x_{mt}$): the factors that help explain $y_t$.\n\nThe general functional form is:\n\n$$y_t = f(x_{1t},\\, x_{2t},\\, \\ldots,\\, x_{mt}) \\tag{1}$$\n\nEquation (1) states that the level of $y_t$ is influenced by the behaviour of variables $x_{1t}, x_{2t}, \\ldots, x_{mt}$, and the relationship is established from historical data.\n\n## Linear Multiple Regression Model (No Lags)\n\nThe standard multiple linear regression model is:\n\n$$y_t = \\beta_0 + \\beta_1 x_{1t} + \\beta_2 x_{2t} + \\cdots + \\beta_m x_{mt} + \\varepsilon_t \\tag{2}$$\n\nIn compact summation form:\n\n$$y_t = \\beta_0 + \\sum_{i=1}^{m} \\beta_i x_{it} + \\varepsilon_t \\tag{3}$$\n\nwhere:\n\n- $\\beta_0$ is the intercept (constant term),\n- $\\beta_i$ is the coefficient for the $i$-th independent variable,\n- $\\varepsilon_t$ is the error (disturbance) term at time $t$,\n- The $x_{it}$ matrix is assumed non-stochastic (fixed), and $y_t$ is a random variable.\n\n## General Model with Lag Variables\n\nA more general model, the **Autoregressive Distributed Lag (ADL)** model, allows both lagged values of the dependent variable and lagged values of the independent variables:\n\n$$y_t = \\beta_0 + \\beta_1 x_{1t} + \\cdots + \\beta_m x_{mt} + \\phi_1 y_{t-1} + \\cdots + \\phi_p y_{t-p} + \\omega_{11} x_{1(t-1)} + \\cdots + \\omega_{pm} x_{m(t-j)} + \\varepsilon_t \\tag{4}$$\n\n::: {.callout-note}\nIncluding lagged values of $y_t$ in the model is one of the most effective remedies for serial correlation. The ADL model is the foundation of the **General-to-Specific** modelling strategy covered later in this chapter.\n:::\n\n---\n\n# Fundamental of OLS Technique\n\n## Ordinary Least Squares (OLS)\n\n**Ordinary Least Squares (OLS)** is the standard method for estimating the parameters of a linear regression model. Its main objective is to **minimise the sum of squared errors**:\n\n$$\\text{Minimise} \\quad \\sum_{t=1}^{n} \\varepsilon_t^2 = \\sum_{t=1}^{n} (y_t - \\hat{y}_t)^2$$\n\nwhere $\\varepsilon_t = y_t - \\hat{y}_t$ is the residual at time $t$.\n\n## Deriving the OLS Estimators (Simple Regression)\n\nConsider a regression model with one independent variable:\n\n$$y_t = \\beta_0 + \\beta_1 x_{1t} + \\varepsilon_t \\tag{5}$$\n\nThe fitted equation is:\n\n$$\\hat{y}_t = \\hat{\\beta}_0 + \\hat{\\beta}_1 x_{1t} \\tag{6}$$\n\nThe residual is:\n\n$$\\varepsilon_t = y_t - \\hat{y}_t = y_t - (\\hat{\\beta}_0 + \\hat{\\beta}_1 x_{1t}) \\tag{7, 8}$$\n\nThe sum of squared errors to minimise:\n\n$$\\sum_{i=1}^{n} \\varepsilon_i^2 = \\sum_{i=1}^{n} \\left[y_t - \\hat{\\beta}_0 - \\hat{\\beta}_1 x_{1t}\\right]^2 \\tag{9}$$\n\n**Partial differentiation with respect to $\\beta_0$**, equating to zero:\n\n$$\\frac{\\partial \\sum_{t=1}^{n} \\varepsilon_t^2}{\\partial \\beta_0} = 2\\sum_{t=1}^{n}\\left(y_t - \\hat{\\beta}_0 - \\hat{\\beta}_1 x_{1t}\\right)(-1) = 0 \\tag{10}$$\n\nThis simplifies (through equations 11--12) to the **first normal equation**:\n\n$$\\sum_{t=1}^{n} y_t = n\\hat{\\beta}_0 + \\hat{\\beta}_1 \\sum_{t=1}^{n} x_{1t} \\tag{13}$$\n\n**Partial differentiation with respect to $\\beta_1$**, equating to zero:\n\n$$\\frac{\\partial \\sum_{t=1}^{n} \\varepsilon_t^2}{\\partial \\beta_1} = \\sum_{t=1}^{n}\\left(y_t - \\hat{\\beta}_0 - \\hat{\\beta}_1 x_{1t}\\right)(-x_{1t}) = 0 \\tag{14}$$\n\nThis gives the **second normal equation**:\n\n$$\\sum_{t=1}^{n} x_{1t} y_t = \\hat{\\beta}_0 \\sum_{t=1}^{n} x_{1t} + \\hat{\\beta}_1 \\sum_{t=1}^{n} x_{1t}^2 \\tag{16}$$\n\nSolving these two normal equations simultaneously yields the OLS estimates $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$.\n\n::: {.callout-note}\nIn practice, R's `lm()` function performs all of these calculations internally using matrix algebra. Understanding the derivation helps you interpret what the function is doing under the hood and why the assumptions matter.\n:::\n\n---\n\n# Issues in the Econometric Construction\n\n## Variable Selection Criteria\n\nVariables included in the model must satisfy two conditions:\n\n1. **Statistical significance** — the variable must have a meaningful statistical relationship with $y_t$.\n2. **Theoretical (logical) justification** — the relationship must be supported by economic theory.\n\nVariable selection is the procedure of choosing a subset (from all possible subsets) of independent variables. The common criterion is to **minimise the squared error** while maintaining theoretical coherence.\n\n### Steps for Model Specification\n\n| Step | Description |\n|---|---|\n| **Step 1** | Identify the appropriate economic theory to select independent variables that explain the dependent variable. |\n| **Step 2** | Ensure sufficient data are available. Rule of thumb: at least **5 observations per independent variable**. |\n| **Step 3** | Examine the relationships among variables using historical data to assess the general fitness of the model. |\n\n## Model Cost\n\n- As model complexity increases, data requirements and computational costs increase.\n- More sophisticated models require more time, specialised software, and greater expertise.\n- A parsimonious model is preferred when it achieves comparable predictive performance at lower cost.\n\n## Model Complexity\n\n- Simple linear models are easy to interpret and visualise.\n- Models with many independent variables are difficult to envisage and may overfit the data.\n- **Principle of parsimony**: if two models have the same explanatory power, prefer the simpler one.\n\n## Future Values of Independent Variables\n\nA key practical challenge in multi-variable forecasting:\n\n$$\\hat{y}_{t+1} = \\hat{\\beta}_0 + \\hat{\\beta}_1 x_{1(t+1)} + \\hat{\\beta}_2 x_{2(t+1)}$$\n\nTo forecast $y_{t+1}$, the analyst must also have (or forecast) $x_{1(t+1)}$ and $x_{2(t+1)}$.\n\n::: {.callout-note}\n**Challenge:** If the future values of independent variables are themselves estimated with error, those errors propagate into the forecast of $y$. This is a key limitation of econometric forecasting compared to univariate methods — more variables means more sources of forecast error.\n:::\n\n---\n\n# Assumptions\n\n## Assumptions Pertaining to the Model\n\nFor OLS estimates to have desirable properties (unbiasedness, efficiency), the following model-level assumptions must hold:\n\n1. **Linearity** — $y_t$ is a linear function of the independent variables.\n2. **Correct specification** — all relevant variables are included; no irrelevant variables are present.\n3. **No multicollinearity** — the $x_t$'s must be mutually independent.\n4. **Sufficient sample size** — the number of observations $n$ must exceed the number of regressors $m$.\n\n## Assumptions Pertaining to the Error Term\n\n1. **IID errors** — the error terms $\\varepsilon_t$ are identically and independently distributed.\n2. **Homoscedasticity** — $\\text{Var}(\\varepsilon_t) = \\sigma^2$ is constant for all $t$.\n3. **No autocorrelation** — $\\text{Cov}(\\varepsilon_t, \\varepsilon_s) = 0$ for all $t \\neq s$.\n4. **Exogeneity** — the independent variables are uncorrelated with the error terms.\n5. **Normality** — $\\varepsilon_t \\sim N(0, \\sigma^2)$.\n\n## Specification Error\n\nA model is **correctly specified** if it includes the correct set of independent variables. Common misspecification situations are:\n\n| Type | Description |\n|---|---|\n| **Under-specification** | Relevant variables are omitted from the model. |\n| **Over-specification** | Irrelevant variables are included in the model. |\n| **Wrong functional form** | Linear model used when the true relationship is non-linear. |\n| **Poor residuals** | Diagnostic checks on residuals indicate systematic patterns. |\n\n---\n\n# Model Estimation Procedure\n\n## Two Main Strategies\n\nTwo main strategies exist for estimating an econometric model:\n\n| Strategy | Description |\n|---|---|\n| **General-to-Specific** | Start with the most general model and systematically remove insignificant variables. Also called *backward stepwise*. |\n| **Specific-to-General** | Start with a simple model and add variables one at a time. Also called *forward stepwise*. |\n\n## General-to-Specific (Backward Stepwise)\n\nThe General-to-Specific approach is based on the **principle of parsimony**:\n\n> *If there are two or more competing explanations of the same phenomenon, each having the same explanatory power, choose the simpler one.*\n\n**Procedure:**\n\n1. Formulate a sufficiently large **unrestricted (general) model** — the ADL model — including all candidate independent variables and their lags:\n\n$$y_t = \\beta_0 + \\sum_{m=1}^{k} \\beta_m x_{mt} + \\sum_{j=1}^{p} \\phi_j y_{t-j} + \\sum_{m=1}^{k}\\sum_{j=1}^{q} \\omega_{mj} x_{m(t-j)} + \\varepsilon_t$$\n\n2. Apply diagnostic tests at each stage.\n3. Drop the **most insignificant** variable (highest $p$-value) at each step — one at a time.\n4. A variable may also be dropped if it registers the **wrong sign** contrary to theoretical expectations.\n5. Repeat until all remaining variables are significant and pass all diagnostics.\n\n::: {.callout-note}\n**Why drop one variable at a time?** The significance of one variable depends on what other variables are in the model. Dropping multiple variables simultaneously can lead to incorrect conclusions about which variables truly matter.\n:::\n\n**Practical considerations for the general model:**\n\n- Maintain a small number of explanatory variables to control cost, avoid multicollinearity, and keep the model interpretable.\n- If multicollinearity exists, the offending variable (usually with the highest VIF) is a candidate for removal.\n\n## Specific-to-General (Forward Stepwise)\n\n**Procedure:**\n\n1. Start with the simplest model, e.g.:\n$$y_t = \\beta_0 + \\beta_1 x_{1t} + \\varepsilon_t \\quad \\text{or} \\quad y_t = \\phi_0 + \\phi_1 y_{t-1} + \\varepsilon_t$$\n\n2. If the model is inadequate or mis-specified, add the next most promising variable (based on correlation with $y_t$).\n3. Repeat until a well-specified model is obtained.\n\n::: {.callout-note}\nIn this course, we primarily use the **General-to-Specific** approach, as illustrated in the worked example with Malaysian car registration data.\n:::\n\n---\n\n# Statistical Validation and Testing Procedure\n\nFailure to satisfy any of the following tests indicates that a model assumption is violated. Remedial action should then be taken: reformulate the model, include new variables, obtain more data, or apply variable transformations.\n\n| Test | Purpose | Decision Rule |\n|---|---|---|\n| **F-test** | Overall model fitness | If $p < 0.05$, at least one variable is significant |\n| **t-test** | Significance of each coefficient | If $p < 0.05$, retain the variable |\n| **Adjusted $R^2$** | Goodness of fit | Higher is better; preferred over $R^2$ |\n| **Breusch-Pagan** | Heteroscedasticity | If $p > 0.05$, variances are constant (no problem) |\n| **Durbin-Watson** | Serial correlation | DW $\\approx$ 2 and $p > 0.05$ means no problem |\n| **VIF** | Multicollinearity | VIF $> 10$ indicates a serious problem |\n\n## General Fitness (F-Test)\n\nThe F-test evaluates the **overall significance** of the model:\n\n- $H_0$: All slope coefficients are zero ($\\beta_1 = \\beta_2 = \\cdots = \\beta_m = 0$).\n- $H_1$: At least one coefficient is non-zero.\n\n**Decision:** If the $p$-value from the F-test is less than 0.05, the model has overall fit and at least one variable is significant. Proceed to examine individual coefficients using t-tests. Otherwise, the model is considered poorly fit.\n\n## Regression Coefficients (t-Test)\n\nAfter confirming the model is overall significant via the F-test, examine each individual coefficient $\\beta_1, \\beta_2, \\ldots, \\beta_m$:\n\n- $H_0$: $\\beta_i = 0$ (variable $i$ has no effect on $y$)\n- $H_1$: $\\beta_i \\neq 0$\n\n**Decision:** If $p < 0.05$, retain the variable. Otherwise, consider removing it from the model.\n\n## Goodness of Fit ($R^2$ and Adjusted $R^2$)\n\nThe **coefficient of determination** $R^2$ measures the proportion of total variation in $y_t$ explained by the regression:\n\n$$R^2 = 1 - \\frac{\\text{SSR}}{\\text{SST}} = 1 - \\frac{\\sum_{t=1}^{n}(y_t - \\hat{y}_t)^2}{\\sum_{t=1}^{n}(y_t - \\bar{y})^2}$$\n\n$R^2 \\in [0, 1]$, where 0 indicates no fit and 1 indicates perfect fit.\n\n**Problem with $R^2$:** It increases mechanically whenever a new variable is added, even if the variable adds no explanatory value. Therefore, use **Adjusted $R^2$**:\n\n$$\\bar{R}^2 = 1 - \\frac{(1 - R^2)(n - 1)}{n - m - 1}$$\n\nwhere $n$ is the number of observations and $m$ is the number of independent variables. Adjusted $R^2$ penalises for adding variables and is the preferred measure of goodness of fit.\n\n## Heteroscedasticity\n\n**Homoscedasticity** means the variance of the error term is constant:\n$$\\text{Var}(\\varepsilon_t) = \\sigma^2 \\quad \\text{for all } t$$\n\nIf this assumption is violated, the errors are **heteroscedastic** — their variance changes over time or across observations. Consequences:\n\n- OLS estimates are no longer the minimum variance (BLUE) estimators.\n- Standard errors and inference become unreliable.\n- Forecasts become less predictable as the forecast horizon extends.\n\n**Breusch-Pagan Test:**\n- $H_0$: Error variance is constant (homoscedastic).\n- $H_1$: Error variance is non-constant (heteroscedastic).\n- **Decision:** If $p > 0.05$, no heteroscedasticity problem. If $p < 0.05$, heteroscedasticity is present — consider transforming the dependent variable (e.g., log transformation).\n\n## Serial Correlation (Autocorrelation)\n\nThe error terms must be uncorrelated across time:\n$$\\text{Cov}(\\varepsilon_t, \\varepsilon_{t-s}) = 0 \\quad \\text{for all } s \\neq 0$$\n\nThe most common form is **first-order autocorrelation**:\n$$\\varepsilon_t = \\rho \\varepsilon_{t-1} + \\nu_t \\tag{17}$$\n\n### Consequences of Autocorrelation\n\nBy repeated substitution of equation (17):\n\n$$\\varepsilon_t = \\rho \\varepsilon_{t-1} + \\nu_t = \\rho^k \\varepsilon_{t-k} + \\sum_{j=0}^{k-1} \\rho^j \\nu_{t-j} \\tag{18}$$\n\nUnder perfect correlation ($\\rho = 1$):\n$$\\varepsilon_t = \\varepsilon_{t-k} + \\sum_{j=1}^{k-1} \\nu_{t-j} \\tag{19}$$\n\n$$\\text{Var}(\\varepsilon_t) = \\sigma^2_\\varepsilon + k\\sigma^2_\\nu$$\n\nSince the variance of $\\varepsilon_t$ **grows with $k$**, forecast accuracy deteriorates as the forecast horizon increases. When $\\rho = 0$, $\\text{Var}(\\varepsilon_t) = \\sigma^2_\\varepsilon$ is constant and there is no serial correlation.\n\n### Durbin-Watson Test\n\n$$DW = \\frac{\\sum_{t=2}^{n}(\\varepsilon_t - \\varepsilon_{t-1})^2}{\\sum_{t=1}^{n} \\varepsilon_t^2} \\tag{20}$$\n\n| DW Value | Interpretation |\n|---|---|\n| DW $< 2$ | Positive serial correlation |\n| DW $\\approx 2$ | No serial correlation |\n| DW $> 2$ | Negative serial correlation |\n\n- **Decision:** If the $p$-value from the Durbin-Watson test is less than 0.05, serial correlation is present.\n- **Remedy:** Include a lag of the dependent variable ($y_{t-1}$) or a lag of an independent variable. Usually, lag 1 is sufficient to resolve the problem.\n\n## Multicollinearity\n\n**Multicollinearity** occurs when two or more independent variables are linearly related to each other.\n\n### Example\n\nConsider $y_t = \\beta_0 + \\beta_1 x_{1t} + \\beta_2 x_{2t} + \\varepsilon_t$ where $x_{1t} = 2x_{2t}$:\n\n$$y_t = \\beta_0 + 2\\beta_1 x_{2t} + \\beta_2 x_{2t} + \\varepsilon_t = \\beta_0 + (2\\beta_1 + \\beta_2)x_{2t} + \\varepsilon_t$$\n\nIt is impossible to separate the individual effects of $x_{1t}$ and $x_{2t}$ — their contributions are **confounded**.\n\n### Consequences\n\n- Standard errors of the coefficients become inflated.\n- Individual variables appear insignificant (high $p$-values) despite the model having a high $R^2$.\n- Signs of coefficients may be reversed relative to theoretical expectations.\n\n### Detection — Variance Inflation Factor (VIF)\n\n$$\\text{VIF}_i = \\frac{1}{1 - R_i^2}$$\n\nwhere $R_i^2$ is the $R^2$ from regressing variable $i$ on all other independent variables.\n\n| VIF | Interpretation |\n|---|---|\n| VIF $< 5$ | No problem |\n| $5 \\leq$ VIF $< 10$ | Moderate concern |\n| VIF $\\geq 10$ | Serious multicollinearity — action required |\n\n### Remedial Actions\n\n1. **Do nothing** if it does not affect model performance or forecasting accuracy.\n2. **Drop the offending variable** — choose the one with the least theoretical support or the highest VIF.\n3. **Increase the sample size** — more data reduces the impact of multicollinearity.\n\n---\n\n# Forecasting Using Econometric Models in R\n\n## Worked Example: Forecasting New Car Registrations in Malaysia\n\nThis section demonstrates the complete step-by-step procedure for building an econometric model for forecasting purposes.\n\n**Objective:** Develop an econometric model to forecast the demand for cars in Malaysia, measured by the **Number of New Car Registrations ('000)**.\n\n### Data Overview\n\n\n\n::: {#tbl-data-head .cell tbl-cap='First six rows of the economic dataset'}\n\n```{.r .cell-code}\nknitr::kable(head(econ), digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n| Year| Number of Car Registration ('000)| BLR (%)| Unemployment Rate (%)| Total Population|   CPI| Total Export| Income|         GDP|\n|----:|---------------------------------:|-------:|---------------------:|----------------:|-----:|------------:|------:|-----------:|\n| 1969|                             21.60|     9.1|                   7.6|         10061684| -0.41|         1.73|    264| 17817535563|\n| 1970|                             23.10|     9.2|                   7.5|         10306508|  1.84|         1.76|    264| 18884189212|\n| 1971|                             25.80|     9.2|                   7.5|         10552557|  1.61|         1.72|    264| 20779153503|\n| 1972|                             29.40|     8.9|                   7.4|         10801619|  3.23|         1.82|    264| 22729992899|\n| 1973|                             31.20|     9.9|                   7.2|         11062664| 10.56|         3.18|    264| 25389647919|\n| 1974|                             41.61|    11.2|                   7.2|         11335187| 17.33|         4.59|    362| 27501726906|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(econ, aes(x = Year, y = `Number of Car Registration ('000)`)) +\n  geom_line(colour = \"steelblue\", linewidth = 0.9) +\n  geom_point(colour = \"steelblue\", size = 1.8) +\n  labs(title = \"New Car Registrations in Malaysia\",\n       x = \"Year\",\n       y = \"Number ('000)\") +\n  theme_ts()\n```\n\n::: {.cell-output-display}\n![Number of new car registrations in Malaysia, 1969--2022](C3-Econometric-Modelling_files/figure-html/fig-car-ts-1.png){#fig-car-ts width=672}\n:::\n:::\n\n\n\n### Variable Names\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check the exact column names before modelling\nnames(econ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Year\"                              \"Number of Car Registration ('000)\"\n[3] \"BLR (%)\"                           \"Unemployment Rate (%)\"            \n[5] \"Total Population\"                  \"CPI\"                              \n[7] \"Total Export\"                      \"Income\"                           \n[9] \"GDP\"                              \n```\n\n\n:::\n:::\n\n\n\nThe dataset contains **54 annual observations** from 1969 to 2022. Based on economic theory, the expected relationships between each independent variable and new car registrations are:\n\n| Independent Variable | Expected Sign | Rationale |\n|---|---|---|\n| Unemployment Rate (%) | Negative | Higher unemployment reduces household income and car purchases |\n| CPI | Negative | Higher prices reduce real purchasing power |\n| BLR (%) | Negative | Higher lending rates raise financing costs, dampening demand |\n| GDP | Positive | Higher national income supports consumer spending |\n| Total Export | Positive | Export growth reflects economic prosperity |\n| Total Population | Positive | More people, more demand for cars |\n| Income | Positive | Higher per capita income directly boosts car demand |\n\n### Creating the Lag Variable\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create lag 1 of number of car registrations\n# This is needed to address serial correlation (see Model 2 onwards)\nlag1 <- c(NA, econ$`Number of Car Registration ('000)`[\n  1:(length(econ$`Number of Car Registration ('000)`) - 1)])\n```\n:::\n\n\n\n---\n\n## Model 1 — Full Model (All Variables, No Lag)\n\nThe first model includes all seven independent variables. This is the **general model** in the General-to-Specific procedure.\n\n$$\\hat{y}_t = \\hat{\\beta}_0 + \\hat{\\beta}_1(\\text{Unemployment}) + \\hat{\\beta}_2(\\text{CPI}) + \\hat{\\beta}_3(\\text{BLR}) + \\hat{\\beta}_4(\\text{GDP}) + \\hat{\\beta}_5(\\text{Export}) + \\hat{\\beta}_6(\\text{Population}) + \\hat{\\beta}_7(\\text{Income})$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1: full model with all independent variables\n# Dependent variable Y: Number of Car Registration ('000)\n# Independent variables X: all economic predictors\nmodel1 <- lm(`Number of Car Registration ('000)` ~\n               `Unemployment Rate (%)` + CPI + `BLR (%)` +\n               GDP + `Total Export` + `Total Population` + Income,\n             data = econ)\n\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `Number of Car Registration ('000)` ~ `Unemployment Rate (%)` + \n    CPI + `BLR (%)` + GDP + `Total Export` + `Total Population` + \n    Income, data = econ)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-133.033  -25.599    6.262   18.042  103.360 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              1.108e+02  1.343e+02   0.825  0.41347    \n`Unemployment Rate (%)` -2.070e+01  7.653e+00  -2.705  0.00953 ** \nCPI                      4.406e-01  2.598e+00   0.170  0.86604    \n`BLR (%)`               -8.711e+00  6.251e+00  -1.394  0.17016    \nGDP                     -1.601e-09  1.156e-09  -1.385  0.17277    \n`Total Export`           1.768e+00  3.860e-01   4.579 3.55e-05 ***\n`Total Population`       1.454e-05  6.130e-06   2.372  0.02192 *  \nIncome                   3.715e-02  3.401e-02   1.092  0.28039    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 46.27 on 46 degrees of freedom\nMultiple R-squared:  0.9673,\tAdjusted R-squared:  0.9623 \nF-statistic: 194.5 on 7 and 46 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Diagnostic tests for Model 1\ncat(\"--- VIF (Multicollinearity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- VIF (Multicollinearity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n`Unemployment Rate (%)`                     CPI               `BLR (%)` \n               3.849078                1.393722                7.000983 \n                    GDP          `Total Export`      `Total Population` \n             414.470181               34.029012               54.943368 \n                 Income \n             170.152327 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Durbin-Watson Test (Serial Correlation) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Durbin-Watson Test (Serial Correlation) ---\n```\n\n\n:::\n\n```{.r .cell-code}\ndurbinWatsonTest(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1       0.4470231      1.101488       0\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Breusch-Pagan Test (Heteroscedasticity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Breusch-Pagan Test (Heteroscedasticity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model1\nBP = 7.8119, df = 7, p-value = 0.3495\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(data.frame(Fitted = fitted(model1), Residuals = residuals(model1)),\n             aes(x = Fitted, y = Residuals)) +\n  geom_point(colour = \"steelblue\", alpha = 0.7) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", colour = \"red\") +\n  labs(title = \"Residuals vs Fitted\", x = \"Fitted values\", y = \"Residuals\") +\n  theme_ts()\n\np2 <- ggplot(data.frame(Residuals = residuals(model1)), aes(sample = Residuals)) +\n  stat_qq(colour = \"steelblue\") +\n  stat_qq_line(colour = \"red\", linetype = \"dashed\") +\n  labs(title = \"Normal Q-Q Plot\") +\n  theme_ts()\n\ngrid.arrange(p1, p2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![Residual diagnostics for Model 1](C3-Econometric-Modelling_files/figure-html/fig-model1-resid-1.png){#fig-model1-resid width=672}\n:::\n:::\n\n\n\n::: {.callout-note}\n**Model 1 Interpretation:**\n\n- The adjusted $R^2$ and F-test are highly significant — the variables collectively explain most of the variation in car registrations.\n- However, **CPI** and **GDP** registered signs *contrary* to theoretical expectations (positive instead of negative/positive as expected in this context).\n- The **VIF of GDP** is extremely high, indicating severe multicollinearity.\n- The **Breusch-Pagan** $p$-value $> 0.05$: no heteroscedasticity problem.\n- The **Durbin-Watson** test is significant ($p < 0.05$): **serial correlation problem exists**.\n\n**Action:** Add the lag variable of new car registration to address the serial correlation.\n:::\n\n---\n\n## Model 2 — Add Lag of Dependent Variable\n\nAdding $y_{t-1}$ (lag 1 of car registrations) is the standard remedy for serial correlation.\n\n$$\\hat{y}_t = \\hat{\\beta}_0 + \\hat{\\beta}_1(\\text{Unemployment}) + \\hat{\\beta}_2(\\text{CPI}) + \\hat{\\beta}_3(\\text{BLR}) + \\hat{\\beta}_4(\\text{GDP}) + \\hat{\\beta}_5(\\text{Export}) + \\hat{\\beta}_6(\\text{Population}) + \\hat{\\beta}_7(\\text{Income}) + \\hat{\\phi}_1 y_{t-1}$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 2: add lag1 to address serial correlation\nmodel2 <- lm(`Number of Car Registration ('000)` ~\n               `Unemployment Rate (%)` + CPI + `BLR (%)` +\n               GDP + `Total Export` + `Total Population` + Income + lag1,\n             data = econ)\n\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `Number of Car Registration ('000)` ~ `Unemployment Rate (%)` + \n    CPI + `BLR (%)` + GDP + `Total Export` + `Total Population` + \n    Income + lag1, data = econ)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-83.653 -14.255   0.009  13.669  94.445 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              1.411e+02  1.094e+02   1.290 0.203828    \n`Unemployment Rate (%)` -1.473e+01  6.132e+00  -2.402 0.020587 *  \nCPI                      3.344e-01  2.154e+00   0.155 0.877331    \n`BLR (%)`               -4.880e+00  4.990e+00  -0.978 0.333483    \nGDP                     -9.560e-10  9.200e-10  -1.039 0.304454    \n`Total Export`           1.196e+00  3.232e-01   3.702 0.000593 ***\n`Total Population`       3.357e-06  5.464e-06   0.614 0.542141    \nIncome                   2.357e-02  2.693e-02   0.875 0.386057    \nlag1                     5.119e-01  9.389e-02   5.453 2.14e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 36.48 on 44 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:   0.98,\tAdjusted R-squared:  0.9764 \nF-statistic: 269.6 on 8 and 44 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"--- VIF (Multicollinearity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- VIF (Multicollinearity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n`Unemployment Rate (%)`                     CPI               `BLR (%)` \n               3.694196                1.493748                7.158650 \n                    GDP          `Total Export`      `Total Population` \n             411.683506               37.556426               67.445528 \n                 Income                    lag1 \n             168.195560               18.671873 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Durbin-Watson Test (Serial Correlation) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Durbin-Watson Test (Serial Correlation) ---\n```\n\n\n:::\n\n```{.r .cell-code}\ndurbinWatsonTest(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1    -0.002775646      1.853213   0.152\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Breusch-Pagan Test (Heteroscedasticity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Breusch-Pagan Test (Heteroscedasticity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model2\nBP = 18.234, df = 8, p-value = 0.01954\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note}\n**Model 2 Interpretation:**\n\n- The DW value improved to approximately 1.85 and $p > 0.05$: **serial correlation problem resolved**.\n- Only **Total Export**, **Unemployment Rate**, and the **lag variable** are statistically significant.\n- **CPI** and **GDP** still show incorrect signs, and GDP has a very high VIF — multicollinearity persists.\n\n**Action:** Drop GDP (most insignificant with highest VIF) from the model.\n:::\n\n---\n\n## Model 3 — Remove GDP\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 3: remove GDP (most insignificant + highest VIF)\nmodel3 <- lm(`Number of Car Registration ('000)` ~\n               `Unemployment Rate (%)` + CPI + `BLR (%)` +\n               `Total Export` + `Total Population` + Income + lag1,\n             data = econ)\n\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `Number of Car Registration ('000)` ~ `Unemployment Rate (%)` + \n    CPI + `BLR (%)` + `Total Export` + `Total Population` + Income + \n    lag1, data = econ)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-77.268 -16.073  -0.469  11.554 104.394 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              1.365e+02  1.094e+02   1.248 0.218566    \n`Unemployment Rate (%)` -1.304e+01  5.918e+00  -2.204 0.032701 *  \nCPI                      1.965e-02  2.134e+00   0.009 0.992694    \n`BLR (%)`               -3.492e+00  4.812e+00  -0.726 0.471846    \n`Total Export`           9.986e-01  2.614e-01   3.820 0.000406 ***\n`Total Population`       4.600e-07  4.703e-06   0.098 0.922522    \nIncome                  -3.264e-03  7.613e-03  -0.429 0.670121    \nlag1                     5.248e-01  9.316e-02   5.633 1.09e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 36.51 on 45 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.9795,\tAdjusted R-squared:  0.9763 \nF-statistic: 307.4 on 7 and 45 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"--- VIF (Multicollinearity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- VIF (Multicollinearity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n`Unemployment Rate (%)`                     CPI               `BLR (%)` \n               3.434997                1.464204                6.645678 \n         `Total Export`      `Total Population`                  Income \n              24.520363               49.886310               13.422505 \n                   lag1 \n              18.349569 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Durbin-Watson Test (Serial Correlation) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Durbin-Watson Test (Serial Correlation) ---\n```\n\n\n:::\n\n```{.r .cell-code}\ndurbinWatsonTest(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1      0.03327008      1.751804   0.068\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Breusch-Pagan Test (Heteroscedasticity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Breusch-Pagan Test (Heteroscedasticity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model3\nBP = 14.423, df = 7, p-value = 0.04416\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note}\n**Model 3 Interpretation:**\n\n- The model improved with higher $R^2$ and no serial correlation problem.\n- However, **CPI** and **Income** registered incorrect signs.\n- **Income** is the most insignificant variable.\n\n**Action:** Drop Income from the model.\n:::\n\n---\n\n## Model 4 — Remove Income\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 4: remove Income (incorrect sign + most insignificant)\nmodel4 <- lm(`Number of Car Registration ('000)` ~\n               `Unemployment Rate (%)` + `BLR (%)` +\n               `Total Export` + `Total Population` + CPI + lag1,\n             data = econ)\n\nsummary(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `Number of Car Registration ('000)` ~ `Unemployment Rate (%)` + \n    `BLR (%)` + `Total Export` + `Total Population` + CPI + lag1, \n    data = econ)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-79.452 -18.570  -0.189  12.885  99.914 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              1.610e+02  9.250e+01   1.740 0.088530 .  \n`Unemployment Rate (%)` -1.420e+01  5.219e+00  -2.721 0.009169 ** \n`BLR (%)`               -3.609e+00  4.762e+00  -0.758 0.452389    \n`Total Export`           9.939e-01  2.588e-01   3.840 0.000374 ***\n`Total Population`      -8.518e-07  3.540e-06  -0.241 0.810923    \nCPI                     -1.456e-01  2.080e+00  -0.070 0.944521    \nlag1                     5.297e-01  9.163e-02   5.781 6.17e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 36.19 on 46 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.9794,\tAdjusted R-squared:  0.9768 \nF-statistic: 365.1 on 6 and 46 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"--- VIF (Multicollinearity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- VIF (Multicollinearity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n`Unemployment Rate (%)`               `BLR (%)`          `Total Export` \n               2.720139                6.624291               24.477286 \n     `Total Population`                     CPI                    lag1 \n              28.777339                1.416478               18.072527 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Durbin-Watson Test (Serial Correlation) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Durbin-Watson Test (Serial Correlation) ---\n```\n\n\n:::\n\n```{.r .cell-code}\ndurbinWatsonTest(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1      0.04457492      1.745045   0.086\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Breusch-Pagan Test (Heteroscedasticity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Breusch-Pagan Test (Heteroscedasticity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model4\nBP = 13.282, df = 6, p-value = 0.03877\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note}\n**Model 4 Interpretation:**\n\n- The model produces a high $R^2$ but most variables remain insignificant — a hallmark of multicollinearity.\n- **Total Population** has an incorrect sign (negative, contrary to the expected positive relationship) and is insignificant.\n\n**Action:** Remove Total Population from the model.\n:::\n\n---\n\n## Model 5 — Remove Total Population\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 5: remove Total Population (incorrect sign + insignificant)\nmodel5 <- lm(`Number of Car Registration ('000)` ~\n               `Unemployment Rate (%)` + `BLR (%)` +\n               `Total Export` + CPI + lag1,\n             data = econ)\n\nsummary(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `Number of Car Registration ('000)` ~ `Unemployment Rate (%)` + \n    `BLR (%)` + `Total Export` + CPI + lag1, data = econ)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-81.417 -17.893   0.529  12.971  98.928 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             146.07589   68.07994   2.146   0.0371 *  \n`Unemployment Rate (%)` -13.82127    4.92741  -2.805   0.0073 ** \n`BLR (%)`                -3.49417    4.69007  -0.745   0.4600    \n`Total Export`            0.95831    0.21034   4.556 3.71e-05 ***\nCPI                       0.03282    1.92420   0.017   0.9865    \nlag1                      0.52062    0.08273   6.293 9.67e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 35.82 on 47 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.9794,\tAdjusted R-squared:  0.9772 \nF-statistic: 447.1 on 5 and 47 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"--- VIF (Multicollinearity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- VIF (Multicollinearity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n`Unemployment Rate (%)`               `BLR (%)`          `Total Export` \n               2.474048                6.558008               16.497116 \n                    CPI                    lag1 \n               1.236596               15.033042 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Durbin-Watson Test (Serial Correlation) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Durbin-Watson Test (Serial Correlation) ---\n```\n\n\n:::\n\n```{.r .cell-code}\ndurbinWatsonTest(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1      0.05141295      1.734915   0.124\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Breusch-Pagan Test (Heteroscedasticity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Breusch-Pagan Test (Heteroscedasticity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model5\nBP = 12.122, df = 5, p-value = 0.03315\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note}\n**Model 5 Interpretation:**\n\n- The model still shows evidence of multicollinearity: high $R^2$ but insignificant variables.\n- **CPI** is the most insignificant variable.\n\n**Action:** Remove CPI from the model.\n:::\n\n---\n\n## Model 6 — Remove CPI\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 6: remove CPI (most insignificant)\nmodel6 <- lm(`Number of Car Registration ('000)` ~\n               `Unemployment Rate (%)` + `BLR (%)` +\n               `Total Export` + lag1,\n             data = econ)\n\nsummary(model6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `Number of Car Registration ('000)` ~ `Unemployment Rate (%)` + \n    `BLR (%)` + `Total Export` + lag1, data = econ)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-81.403 -17.873   0.738  13.383  98.933 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             146.08660   67.36439   2.169  0.03510 *  \n`Unemployment Rate (%)` -13.82329    4.87442  -2.836  0.00667 ** \n`BLR (%)`                -3.47933    4.56045  -0.763  0.44924    \n`Total Export`            0.95889    0.20540   4.669 2.47e-05 ***\nlag1                      0.52038    0.08062   6.455 5.04e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 35.45 on 48 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.9794,\tAdjusted R-squared:  0.9777 \nF-statistic: 570.8 on 4 and 48 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"--- VIF (Multicollinearity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- VIF (Multicollinearity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n`Unemployment Rate (%)`               `BLR (%)`          `Total Export` \n               2.472613                6.332415               16.065072 \n                   lag1 \n              14.580335 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Durbin-Watson Test (Serial Correlation) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Durbin-Watson Test (Serial Correlation) ---\n```\n\n\n:::\n\n```{.r .cell-code}\ndurbinWatsonTest(model6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1      0.05149487      1.734734    0.15\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Breusch-Pagan Test (Heteroscedasticity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Breusch-Pagan Test (Heteroscedasticity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(model6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model6\nBP = 11.858, df = 4, p-value = 0.01844\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note}\n**Model 6 Interpretation:**\n\n- After removing CPI, the model improved significantly: high $R^2$ with three significant variables.\n- The Durbin-Watson value confirms **no serial correlation problem**.\n- However, VIF values for **Total Export** and the lag variable indicate multicollinearity still exists between these two variables.\n\n**Action:** Remove Total Export from the model.\n:::\n\n---\n\n## Model 7 — Final Model (Remove Total Export)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 7: final model — remove Total Export\n# Remaining variables: Unemployment Rate, BLR, lag1\nmodel7 <- lm(`Number of Car Registration ('000)` ~\n               `Unemployment Rate (%)` + `BLR (%)` + lag1,\n             data = econ)\n\nsummary(model7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `Number of Car Registration ('000)` ~ `Unemployment Rate (%)` + \n    `BLR (%)` + lag1, data = econ)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-86.523 -20.412  -0.523  17.512 180.560 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             264.93628   74.43585   3.559 0.000838 ***\n`Unemployment Rate (%)` -16.68328    5.77138  -2.891 0.005715 ** \n`BLR (%)`               -13.84240    4.75453  -2.911 0.005402 ** \nlag1                      0.78071    0.06949  11.235 3.66e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 42.31 on 49 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.9701,\tAdjusted R-squared:  0.9682 \nF-statistic: 529.2 on 3 and 49 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"--- VIF (Multicollinearity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- VIF (Multicollinearity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n`Unemployment Rate (%)`               `BLR (%)`                    lag1 \n               2.433558                4.832143                7.604651 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Durbin-Watson Test (Serial Correlation) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Durbin-Watson Test (Serial Correlation) ---\n```\n\n\n:::\n\n```{.r .cell-code}\ndurbinWatsonTest(model7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1     -0.06392779      1.755684   0.192\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n--- Breusch-Pagan Test (Heteroscedasticity) ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Breusch-Pagan Test (Heteroscedasticity) ---\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(model7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model7\nBP = 4.4204, df = 3, p-value = 0.2195\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- ggplot(data.frame(Fitted = fitted(model7), Residuals = residuals(model7)),\n             aes(x = Fitted, y = Residuals)) +\n  geom_point(colour = \"steelblue\", alpha = 0.7) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", colour = \"red\") +\n  labs(title = \"Residuals vs Fitted (Model 7)\", x = \"Fitted values\", y = \"Residuals\") +\n  theme_ts()\n\np4 <- ggplot(data.frame(Residuals = residuals(model7)), aes(sample = Residuals)) +\n  stat_qq(colour = \"steelblue\") +\n  stat_qq_line(colour = \"red\", linetype = \"dashed\") +\n  labs(title = \"Normal Q-Q Plot (Model 7)\") +\n  theme_ts()\n\ngrid.arrange(p3, p4, ncol = 2)\n```\n\n::: {.cell-output-display}\n![Residual diagnostics for the final model (Model 7)](C3-Econometric-Modelling_files/figure-html/fig-model7-resid-1.png){#fig-model7-resid width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_df <- data.frame(\n  Year    = econ$Year[!is.na(lag1)],\n  Actual  = econ$`Number of Car Registration ('000)`[!is.na(lag1)],\n  Fitted  = fitted(model7)\n)\n\nggplot(fit_df, aes(x = Year)) +\n  geom_line(aes(y = Actual, colour = \"Actual\"),   linewidth = 0.9) +\n  geom_line(aes(y = Fitted, colour = \"Fitted\"),\n            linewidth = 0.9, linetype = \"dashed\") +\n  scale_colour_manual(values = c(\"Actual\" = \"steelblue\", \"Fitted\" = \"#d73027\")) +\n  labs(title = \"New Car Registrations: Actual vs Fitted (Model 7)\",\n       x = \"Year\", y = \"Number ('000)\", colour = NULL) +\n  theme_ts()\n```\n\n::: {.cell-output-display}\n![Actual vs fitted values for Model 7 (final model)](C3-Econometric-Modelling_files/figure-html/fig-model7-fit-1.png){#fig-model7-fit width=672}\n:::\n:::\n\n\n\n::: {.callout-note}\n**Model 7 Interpretation (Final Model):**\n\n- The model is overall **highly significant** (F-test $p < 0.05$).\n- All three variables — **Unemployment Rate**, **BLR**, and the **lag of car registrations** — are statistically significant.\n- **No serial correlation**: DW $\\approx 2$, $p > 0.05$.\n- **No multicollinearity**: all VIF values are well below 10.\n- **No heteroscedasticity**: Breusch-Pagan $p > 0.05$.\n- All signs are consistent with economic theory.\n:::\n\n---\n\n## The Final Estimated Equation\n\nThe final estimated model is:\n\n$$\\hat{y}_t = 264.94 - 16.68\\, x_{1t} - 13.84\\, x_{2t} + 0.78\\, y_{t-1}$$\n\nwhere:\n\n- $\\hat{y}_t$ = estimated number of new car registrations ('000) in year $t$,\n- $x_{1t}$ = Unemployment Rate (%) in year $t$,\n- $x_{2t}$ = Base Lending Rate, BLR (%) in year $t$,\n- $y_{t-1}$ = lag 1 of new car registrations ('000).\n\n### Interpretation of Coefficients\n\n| Coefficient | Value | Interpretation |\n|---|---|---|\n| Intercept | 264.94 | Baseline car registrations when all predictors are zero |\n| Unemployment Rate | $-16.68$ | A 1 percentage-point increase in unemployment reduces car demand by approximately **16,680 units** |\n| BLR | $-13.84$ | A 1 percentage-point increase in BLR reduces car demand by approximately **13,840 units** |\n| Lag of car registrations | $+0.78$ | If car registrations increased by 1,000 last year, demand this year increases by approximately **780 units** |\n\nAll signs are consistent with economic theory: higher unemployment and higher borrowing costs both suppress consumer demand for cars, while past registration levels exhibit strong positive persistence.\n\n---\n\n## Forecasting with the Final Model\n\n### Point Forecast for 2023\n\nGiven:\n\n- Unemployment Rate for 2023: $x_{1,2023} = 3.3\\%$\n- BLR for 2023: $x_{2,2023} = 6.89\\%$\n- Number of car registrations in 2022: $y_{2022} = 744.78$ ('000)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract coefficients from the final model\ncoefs <- coef(model7)\ncat(\"Model coefficients:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel coefficients:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(round(coefs, 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            (Intercept) `Unemployment Rate (%)`               `BLR (%)` \n               264.9363                -16.6833                -13.8424 \n                   lag1 \n                 0.7807 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Future values of independent variables for 2023\nunemp_2023 <- 3.3     # Unemployment Rate (%)\nblr_2023   <- 6.89    # BLR (%)\ny_2022     <- 744.78  # Car registrations in 2022 ('000)\n\n# One-step-ahead forecast\ny_hat_2023 <- coefs[\"(Intercept)\"] +\n              coefs[\"`Unemployment Rate (%)`\"] * unemp_2023 +\n              coefs[\"`BLR (%)`\"] * blr_2023 +\n              coefs[\"lag1\"] * y_2022\n\ncat(\"\\nForecast for 2023 (number of new car registrations, '000):\",\n    round(y_hat_2023, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nForecast for 2023 (number of new car registrations, '000): 695.96 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Forecast in actual units:\", round(y_hat_2023 * 1000), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nForecast in actual units: 695961 \n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note}\n**Forecasting caveat:** The quality of this forecast depends on how accurately we know (or can forecast) the unemployment rate and BLR for 2023. If those values are themselves uncertain, the forecast error will be larger than the model's in-sample statistics suggest.\n:::\n\n### Model Selection Summary Table\n\n\n\n::: {#tbl-model-summary .cell tbl-cap='Summary of all models in the General-to-Specific procedure'}\n\n```{.r .cell-code}\nmodel_summary <- data.frame(\n  Model    = paste0(\"Model \", 1:7),\n  Variables_Dropped = c(\n    \"None (full model)\",\n    \"— (add lag1)\",\n    \"GDP removed\",\n    \"Income removed\",\n    \"Total Population removed\",\n    \"CPI removed\",\n    \"Total Export removed\"\n  ),\n  Adj_R2   = c(\n    round(summary(model1)$adj.r.squared, 4),\n    round(summary(model2)$adj.r.squared, 4),\n    round(summary(model3)$adj.r.squared, 4),\n    round(summary(model4)$adj.r.squared, 4),\n    round(summary(model5)$adj.r.squared, 4),\n    round(summary(model6)$adj.r.squared, 4),\n    round(summary(model7)$adj.r.squared, 4)\n  ),\n  DW_pval  = c(\n    round(durbinWatsonTest(model1)$p, 3),\n    round(durbinWatsonTest(model2)$p, 3),\n    round(durbinWatsonTest(model3)$p, 3),\n    round(durbinWatsonTest(model4)$p, 3),\n    round(durbinWatsonTest(model5)$p, 3),\n    round(durbinWatsonTest(model6)$p, 3),\n    round(durbinWatsonTest(model7)$p, 3)\n  ),\n  BP_pval  = c(\n    round(bptest(model1)$p.value, 3),\n    round(bptest(model2)$p.value, 3),\n    round(bptest(model3)$p.value, 3),\n    round(bptest(model4)$p.value, 3),\n    round(bptest(model5)$p.value, 3),\n    round(bptest(model6)$p.value, 3),\n    round(bptest(model7)$p.value, 3)\n  )\n)\n\nknitr::kable(model_summary,\n             col.names = c(\"Model\", \"Change from Previous\",\n                           \"Adj. R²\", \"DW p-value\", \"BP p-value\"),\n             align = \"lllll\")\n```\n\n::: {.cell-output-display}\n\n\n|Model   |Change from Previous     |Adj. R<U+00B2> |DW p-value |BP p-value |\n|:-------|:------------------------|:--------------|:----------|:----------|\n|Model 1 |None (full model)        |0.9623         |0.000      |0.349      |\n|Model 2 |<U+2014> (add lag1)      |0.9764         |0.156      |0.020      |\n|Model 3 |GDP removed              |0.9763         |0.082      |0.044      |\n|Model 4 |Income removed           |0.9768         |0.110      |0.039      |\n|Model 5 |Total Population removed |0.9772         |0.122      |0.033      |\n|Model 6 |CPI removed              |0.9777         |0.176      |0.018      |\n|Model 7 |Total Export removed     |0.9682         |0.194      |0.220      |\n\n\n:::\n:::\n\n\n\n---\n\n# Summary\n\nThis chapter covered the complete framework for **econometric modelling** in time series forecasting. The key takeaways are:\n\n1. **Model Structure:** Econometric models relate a dependent variable to multiple independent (explanatory) variables, grounded in economic theory. The ADL model incorporates both current and lagged variables.\n\n2. **OLS Estimation:** Ordinary Least Squares minimises the sum of squared residuals. Understanding its derivation helps interpret model output and diagnose problems.\n\n3. **Issues in Model Construction:** Variable selection must balance statistical significance with theoretical justification. Practical challenges include model cost, complexity, and the need for future values of predictors.\n\n4. **Assumptions:** Five key assumptions govern OLS — linearity, correct specification, no multicollinearity, homoscedasticity, and no serial correlation. Violations require diagnostic tests and remedial action.\n\n5. **Model Estimation Strategies:**\n   - **General-to-Specific** (backward): Start with the full model and systematically drop the most insignificant variable at each stage until a parsimonious model is reached.\n   - **Specific-to-General** (forward): Start simple and add variables one at a time.\n\n6. **Statistical Validation:** A valid model must pass six diagnostic tests: F-test, t-tests, adjusted $R^2$, Breusch-Pagan (heteroscedasticity), Durbin-Watson (serial correlation), and VIF (multicollinearity).\n\n7. **Worked Example:** The final model for Malaysian new car registrations identified **Unemployment Rate**, **BLR**, and the **lag of car registrations** as the significant determinants. The model satisfies all diagnostic conditions and produces an interpretable, parsimonious equation.\n\n---\n\n# References\n\n- Mohd Alias Lazim (2013). *Introductory Business Forecasting: A Practical Approach*, 3rd ed. UPENA, UiTM. ISBN: 978-983-3643.\n- Department of Statistics Malaysia. Open Data Catalogue. <https://open.dosm.gov.my/data-catalogue>\n- World Bank Open Data. <https://data.worldbank.org>\n- Gujarati, D. N. & Porter, D. C. (2009). *Basic Econometrics*, 5th ed. McGraw-Hill.\n- Hendry, D. F. & Doornik, J. A. (2014). *Empirical Model Discovery and Theory Evaluation*. MIT Press.\n",
    "supporting": [
      "C3-Econometric-Modelling_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}